//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.13 at 03:50:40 PM WEST 
//


package com.example.clientwebservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agentDetails" type="{http://example.com/agentservice}agentDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agentDetails"
})
@XmlRootElement(name = "createAgentRequest")
public class CreateAgentRequest {

    @XmlElement(required = true)
    protected AgentDetails agentDetails;

    /**
     * Gets the value of the agentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AgentDetails }
     *     
     */
    public AgentDetails getAgentDetails() {
        return agentDetails;
    }

    /**
     * Sets the value of the agentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentDetails }
     *     
     */
    public void setAgentDetails(AgentDetails value) {
        this.agentDetails = value;
    }

}
